### ISSUE TITLE
А куда делись более старые статьи?

### ISSUE THREAD

**Issue by ademaro** [nicothin/nicothin.github.io#7]
Привет.

Раньше студентов отправлял сюда почитать: http://web.archive.org/web/20171213033758/https://nicothin.pro/page/dostupnost-veb-stranicy но на сайте статьи уже нет. С чем это связано?

**Comment by nicothin** [comment]
Эту — не помню из-за чего выпилил.
Она более-менее нормальная, сейчас верну.

**Comment by nicothin** [comment]
@ademaro https://nicothin.pro/page/dostupnost-veb-stranicy
